const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Batavia crespa",
      price: 401,
      image: require("./images/img01.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
      cantidad: 1786,
      nombreProveedor: "El Deposito",
      precioAdquirido: 25,
      fechaAdquirido: "03/01/2024",

      
    },
    {
      id: 2,
      title: "Brocoli",
      price: 304,
      image: require("./images/img02.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
      cantidad: 1445,
      nombreProveedor: "El Deposito",
      precioAdquirido: 30,
      fechaAdquirido: "03/01/2024",
    },
    {
      id: 3,
      title: "Tomate",
      price: 475,
      image: require("./images/img03.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325289&w=1000",
      cantidad: 144,
      nombreProveedor: "El Deposito",
      precioAdquirido: 35,
      fechaAdquirido: "03/02/2024",
    },
    {
      id: 4,
      title: "Cilantro",
      price: 399,
      image: require("./images/img04.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 421,
      nombreProveedor: "El Deposito",
      precioAdquirido: 50,
      fechaAdquirido: "04/02/2024",
      
    },
    {
      id: 5,
      title: "Cebolla de huevo morada",
      price: 405,
      image: require("./images/img05.jpg"),
      category: "verduras",
      img1: " https://stockx-360.imgix.net/Nike-Dunk-Low-SP-Kentucky/Images/Nike-Dunk-Low-SP-Kentucky/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
      cantidad: 1441,
      nombreProveedor: "El Deposito",
      precioAdquirido: 100,
      fechaAdquirido: "13/05/2024",
    },
    {
      id: 6,
      title: "Cebolla de huevo blanca",
      price: 285,
      image: require("./images/img06.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-University-Red/Images/Nike-Dunk-Low-Off-White-University-Red/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606321824&w=1000",
      cantidad: 150,
      nombreProveedor: "El Deposito",
      precioAdquirido: 100,
      fechaAdquirido: "23/06/2024",
    },
    {
      id: 7,
      title: "Cabeza de Ajo",
      price: 360,
      image: require("./images/img07.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Air-Max-2-Light-Atmos/Images/Nike-Air-Max-2-Light-Atmos/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606320966&w=1000",
      cantidad: 2440,
      nombreProveedor: "El Deposito",
      precioAdquirido: 102,
      fechaAdquirido: "03/01/2024",

    },
    {
      id: 8,
      title: "Cebolla",
      price: 335,
      image: require("./images/img08.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Clot-Blue-Silk/Images/Nike-Air-Force-1-Low-Clot-Blue-Silk/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325265&w=1000",
      cantidad: 245,
      nombreProveedor: "El Deposito",
      precioAdquirido: 70,
      fechaAdquirido: "03/02/2024",

    },
    {
      id: 9,
      title: "Papa lavada",
      price: 799,
      image: require("./images/img09.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Images/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606323250&w=1000",
      cantidad: 350,
      nombreProveedor: "El Deposito",
      precioAdquirido: 63,
      fechaAdquirido: "03/01/2024",

    },
    {
      id: 10,
      title: "Zanahoria delgada",
      price: 501,
      image: require("./images/img10.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-High-Black-Varsity-Maize/Images/Nike-Dunk-High-Black-Varsity-Maize/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609445259&w=1000",
      cantidad: 100,
      nombreProveedor: "El Deposito",
      precioAdquirido: 40,
      fechaAdquirido: "03/02/2024",

    },
    {
      id: 11,
      title: "Pepino",
      price: 377,
      image: require("./images/img011.jpg"),
      category: "verduras",
      img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
      cantidad: 200,
      nombreProveedor: "El Deposito",
      precioAdquirido: 20,
      fechaAdquirido: "03/01/2024",

    },
  ],
};

// Calcula la ganancia para cada elemento del array
data.items = data.items.map(item => ({
  ...item,
  ganancia: item.price - item.precioAdquirido
}));

export default data;
